live_loop :hmusic do
	sample "/s/flute.wav"
	sample "/s/flute.wav"
	sample :drum_bass_hard
	sample "/s/alo.wav"
	sample "/s/alo.wav"
	sample :drum_bass_hard
	sample "/s/alo.wav"
	sample "/s/alo.wav"
	sleep 7.5e-2
	sleep 7.5e-2
	sleep 7.5e-2
	sleep 7.5e-2
	sample :drum_snare_hard
	sample :drum_snare_hard
	sleep 7.5e-2
	sleep 7.5e-2
	sleep 7.5e-2
	sample :drum_bass_hard
	sample :drum_bass_hard
	sleep 7.5e-2
	sample :drum_bass_hard
	sample :drum_bass_hard
	sleep 7.5e-2
	sleep 7.5e-2
	sample :drum_bass_hard
	sample :drum_bass_hard
	sleep 7.5e-2
	sleep 7.5e-2
	sample :drum_snare_hard
	sample :drum_snare_hard
	sleep 7.5e-2
	sleep 7.5e-2
	sleep 7.5e-2
	sample "/s/auau.wav"
	sample "/s/auau.wav"
	sample "/s/auau.wav"
	sample "/s/auau.wav"
	sleep 7.5e-2
	sample :drum_bass_hard
	sample :drum_bass_hard
	sleep 7.5e-2
	sleep 7.5e-2
	sleep 7.5e-2
	sleep 7.5e-2
	sample :drum_snare_hard
	sample :drum_snare_hard
	sleep 7.5e-2
	sleep 7.5e-2
	sleep 7.5e-2
	sample :drum_bass_hard
	sample :drum_bass_hard
	sleep 7.5e-2
	sample :drum_bass_hard
	sample :drum_bass_hard
	sleep 7.5e-2
	sleep 7.5e-2
	sample :drum_bass_hard
	sample :drum_bass_hard
	sleep 7.5e-2
	sleep 7.5e-2
	sample :drum_snare_hard
	sample :drum_snare_hard
	sleep 7.5e-2
	sleep 7.5e-2
	sleep 7.5e-2
	sleep 7.5e-2
	sample :drum_bass_hard
	sample "/s/alo.wav"
	sample "/s/alo.wav"
	sleep 7.5e-2
	sleep 7.5e-2
	sleep 7.5e-2
	sleep 7.5e-2
	sample :drum_snare_hard
	sleep 7.5e-2
	sleep 7.5e-2
	sleep 7.5e-2
	sample :drum_bass_hard
	sleep 7.5e-2
	sample :drum_bass_hard
	sleep 7.5e-2
	sleep 7.5e-2
	sample :drum_bass_hard
	sleep 7.5e-2
	sleep 7.5e-2
	sample :drum_snare_hard
	sleep 7.5e-2
	sleep 7.5e-2
	sleep 7.5e-2
	sample "/s/auau.wav"
	sample "/s/auau.wav"
	sleep 7.5e-2
	sample :drum_bass_hard
	sleep 7.5e-2
	sleep 7.5e-2
	sleep 7.5e-2
	sleep 7.5e-2
	sample :drum_snare_hard
	sleep 7.5e-2
	sleep 7.5e-2
	sleep 7.5e-2
	sample :drum_bass_hard
	sleep 7.5e-2
	sample :drum_bass_hard
	sleep 7.5e-2
	sleep 7.5e-2
	sample :drum_bass_hard
	sleep 7.5e-2
	sleep 7.5e-2
	sample :drum_snare_hard
	sleep 7.5e-2
	sleep 7.5e-2
	sleep 7.5e-2
	sleep 7.5e-2
end